### ISSUE TITLE
The log is hard to copy

### ISSUE THREAD

**Issue by rugk** [threema-ch/compose-area#35]
If you try to copy the log on your websites (because you want to report a bug), you can hardly select and copy all the log, because when you click there, it does log a click event in the log itself… (destroying your selection)

## Possible solutions
* Copy all button?
* ignore events for clicks there?
* do not log outside clicks?

**Comment by rugk** [comment]
same for any input field, actually…

**Comment by dbrgn** [comment]
We don't handle click events in the log view, only selection changes. Selection changes need to be tracked on document level to work properly.

Since this is only a simple demo, I'll close this issue for now (if necessary, a screenshot or screen capture video could be created to demonstrate a problem).
