### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by holtwick** [threema-ch/compose-area#70]
Thanks for releasing the code to open source! Threema is awesome!

I just wondered, and maybe other visitors do as well, what might be the reason to choose Rust and WASM to implement the "compose area" instead of pure JS? 

Working in the field myself for years I know how hard it is to get `contenteditable` doing what it should. I personally settled on [ProseMirror](https://prosemirror.net/)

Sorry for my curiosity ;)

**Comment by dbrgn** [comment]
Hi @holtwick. Yeah, contenteditable is horrible. The original goal was to dispatch all input events to a backend that then uses a virtual DOM to achieve consistent and deterministic state across all browsers.

Unfortunately while implementing we discovered that this approach doesn't work, because the input events across browsers just don't work properly. It would have worked on modern desktop browsers, but you can forget about it working on mobile devices.

But at that point we already had a Rust codebase so we stuck with it. Rust makes it much easier to handle all possible error cases and everything can be unit tested. I simply changed the approach from "handle all input events and update the DOM" to "handle emoji insertion events in a consistent and well-tested way".

WASM is still has a few rough corners, but all in all I'm quite happy with how it turned out. Main difficulty in integrating it into a JS codebase is that it needs to be loaded asynchronously, but WebPack handles that well.

Hope that answered your curiosity :slightly_smiling_face:

**Comment by holtwick** [comment]
Yes absolutely :) Thanks.
